name: Deploy to GitHub Pages
on:
  push:
    branches: [ master ] # Khi bạn push lên branch main thì nó chạy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Đẩy toàn bộ nội dung thư mục hiện tại